"""empty message

Revision ID: 4a2d2b1447dd
Revises: 57346adefccf
Create Date: 2021-02-08 11:17:22.475239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2d2b1447dd'
down_revision = '57346adefccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))

    with op.batch_alter_table('footer', schema=None) as batch_op:
        batch_op.drop_column('connect')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('footer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connect', sa.VARCHAR(length=55), nullable=True))

    with op.batch_alter_table('connect', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
