"""empty message

Revision ID: 4c272fab4729
Revises: 63e19614fc4a
Create Date: 2021-02-07 19:54:44.199640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c272fab4729'
down_revision = '63e19614fc4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('skill_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('text', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'skill', ['skill_id'], ['id'])
        batch_op.drop_column('about_id')
        batch_op.drop_column('about_title')
        batch_op.drop_column('about_text')

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('skill_id')
        batch_op.drop_column('about_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('skill_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'about', ['about_id'], ['about_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_text', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('about_title', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('about_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('title')
        batch_op.drop_column('text')
        batch_op.drop_column('skill_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
