"""empty message

Revision ID: 75e79d473885
Revises: b5140640a6b2
Create Date: 2021-02-09 01:26:06.899870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e79d473885'
down_revision = 'b5140640a6b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dribble', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connect', schema=None) as batch_op:
        batch_op.drop_column('dribble')

    # ### end Alembic commands ###
