"""empty message

Revision ID: 94db9adacd8d
Revises: a0e90aff6ecb
Create Date: 2021-02-08 10:25:12.416336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94db9adacd8d'
down_revision = 'a0e90aff6ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('pinterest', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connect')
    # ### end Alembic commands ###
