"""empty message

Revision ID: a0e90aff6ecb
Revises: 8aed1856b5a8
Create Date: 2021-02-08 09:25:06.348280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e90aff6ecb'
down_revision = '8aed1856b5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
