"""empty message

Revision ID: a307eac11e9a
Revises: f17212a1a645
Create Date: 2021-02-08 11:01:06.701835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a307eac11e9a'
down_revision = 'f17212a1a645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('footer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('elaqe', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('text', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('footer', schema=None) as batch_op:
        batch_op.drop_column('title')
        batch_op.drop_column('text')
        batch_op.drop_column('name')
        batch_op.drop_column('elaqe')

    # ### end Alembic commands ###
