"""empty message

Revision ID: b719f5cd34f0
Revises: 75e79d473885
Create Date: 2021-02-09 01:26:14.298309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b719f5cd34f0'
down_revision = '75e79d473885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connect', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dribble', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connect', schema=None) as batch_op:
        batch_op.drop_column('dribble')

    # ### end Alembic commands ###
