"""empty message

Revision ID: c00a8bc688e2
Revises: 
Create Date: 2021-02-09 00:37:26.542758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00a8bc688e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
