"""empty message

Revision ID: f17212a1a645
Revises: 94db9adacd8d
Create Date: 2021-02-08 10:25:21.487448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f17212a1a645'
down_revision = '94db9adacd8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instagram', sa.String(), nullable=True),
    sa.Column('pinterest', sa.String(), nullable=True),
    sa.Column('twitter', sa.String(), nullable=True),
    sa.Column('facebook', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connect')
    # ### end Alembic commands ###
